import { Roboto, Poppins } from 'next/font/google';
import './global-styles/reset.css';
const inter = Poppins({ subsets: ['latin'], weight: '400' });

export const metadata = {
  title: 'Plant app',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
