import { Roboto } from 'next/font/google';

const inter = Roboto({ subsets: ['greek'], weight: '400' });

export const metadata = {
  title: 'Plant app',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
